package com.winapp.saperpSQL.model

data class ExpenseSaveRequestMaster(
    var CurrencyRate: String?,
    var CurrentDateTime: String?,
    var DelCustomerName: String?,
    var InvType: String?,
    var Mode: String?,
    var PONo: String?,
    var POStatus: String?,
    var PurchaseInvoiceDetails: List<ExpensePurchaseInvoiceDetail>,
    var SONo: Any?,
    var SOType: String?,
    var Signature: String?,
    var VendorCode: String?,
    var VendorName: String?,
    var address: String?,
    var billDiscount: Int?,
    var billDiscountPercentage: String?,
    var city: String?,
    var companyCode: String?,
    var companyName: String?,
    var createUser: String?,
    var creditLimit: String?,
    var currencyCode: String?,
    var currencyName: String?,
    var currencyvarue: String?,
    var delAddress1: String?,
    var delAddress2: Any?,
    var delAddress3: Any?,
    var delPhoneNo: String?,
    var deliveryCode: String?,
    var haveTax: Boolean,
    var itemDiscount: String?,
    var locationCode: String?,
    var modifyUser: String?,
    var netTotal: String?,
    var poDate: String?,
    var postalCode: String?,
    var status: String?,
    var stockUpdated: String?,
    var street: String?,
    var subTotal: String?,
    var taxCode: String?,
    var taxPerc: String?,
    var taxTotal: String?,
    var taxType: String?,
    var total: String?,
    var totalDiscount: String?
) {
    constructor() :this(""
    ,"","",
        "","",
        "","O", emptyList(),"","","","","","",0,
        "","","","","","","","",
        "","", "","","","",false,
        "","","", "","","","","1","",
        "","","","0.00", "","","0.0")
}